# Generated by Django 3.2.9 on 2021-12-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_theorder_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorder',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thepo',
            name='po_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
