# Generated by Django 3.2.9 on 2021-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_remove_monthlyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
