# Generated by Django 3.2.9 on 2021-12-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_auto_20211230_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='KapasFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_request_number', models.CharField(max_length=200)),
                ('capa_request_date', models.DateField(verbose_name='%d,%m,%Y')),
                ('source_reference_no', models.CharField(max_length=200)),
                ('finding_source_date', models.DateField(verbose_name='%d,%m,%Y')),
                ('finding_no', models.CharField(max_length=200)),
                ('finding_description', models.TextField(max_length=2000)),
                ('finding_category', models.CharField(max_length=20)),
                ('hosting_department', models.CharField(max_length=200)),
                ('capa', models.TextField()),
                ('due_date', models.DateField(verbose_name='%d,%m,%Y')),
                ('capa_s_responsible_department', models.CharField(max_length=200)),
                ('comliance_extra_comments', models.CharField(max_length=200)),
                ('final_status', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('justification_for_modification', models.CharField(max_length=200)),
                ('department_extra_comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
