# Generated by Django 3.2.9 on 2021-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_monthlyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynotes',
            name='area',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dailynotes',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
