# Generated by Django 3.2.9 on 2021-11-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_auto_20211119_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='user',
        ),
    ]
