# Generated by Django 3.2.9 on 2021-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_kapasfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapasfollowup',
            name='capa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='capa_request_date',
            field=models.DateField(blank=True, null=True, verbose_name='%d,%m,%Y'),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='capa_request_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='capa_s_responsible_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='comliance_extra_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='%d,%m,%Y'),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='final_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='finding_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='finding_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='finding_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='finding_source_date',
            field=models.DateField(blank=True, null=True, verbose_name='%d,%m,%Y'),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='hosting_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='justification_for_modification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='source_reference_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
