# Generated by Django 3.2.9 on 2021-12-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_auto_20211230_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapasfollowup',
            name='capa_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='finding_source_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
