# Generated by Django 3.2.9 on 2021-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0009_monthlyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMonthMenets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_title', models.CharField(max_length=200)),
                ('task1', models.CharField(max_length=200)),
                ('task1date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task2', models.CharField(blank=True, max_length=200, null=True)),
                ('task2date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task3', models.CharField(blank=True, max_length=200, null=True)),
                ('task3date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task4', models.CharField(blank=True, max_length=200, null=True)),
                ('task4date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task5', models.CharField(blank=True, max_length=200, null=True)),
                ('task5date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task6', models.CharField(blank=True, max_length=200, null=True)),
                ('task6date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task7', models.CharField(blank=True, max_length=200, null=True)),
                ('task7date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task8', models.CharField(blank=True, max_length=200, null=True)),
                ('task8date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task9', models.CharField(blank=True, max_length=200, null=True)),
                ('task9date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task10', models.CharField(blank=True, max_length=200, null=True)),
                ('task10date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
