# Generated by Django 3.2.9 on 2021-11-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0010_currentmonthmenets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentMonthMenets',
        ),
    ]
