# Generated by Django 3.2.9 on 2021-12-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0011_alter_kapasfollowup_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoffer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='theorder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='thepo',
            name='area',
        ),
        migrations.AddField(
            model_name='theorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('DELIVERED', 'delivered'), ('On_Way', 'on_way')], default='on_way', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thepo',
            name='po_status',
            field=models.CharField(blank=True, choices=[('DELIVERED', 'delivered'), ('On_Way', 'on_way')], default='on_way', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailynotes',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY'), ('Ousuka-Techno', 'Ousuka-Techno'), ('Eltartosiah', 'Eltartosiah'), ('Bielomatic', 'Bielomatic'), ('Lubricant_Engineers', 'Lubricant_Engineers'), ('Omega', 'Omega')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kapasfollowup',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='Search_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='Sp_Branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='description1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='item_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='short_item_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theoffer',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY'), ('Ousuka-Techno', 'Ousuka-Techno'), ('Eltartosiah', 'Eltartosiah'), ('Bielomatic', 'Bielomatic'), ('Lubricant_Engineers', 'Lubricant_Engineers'), ('Omega', 'Omega')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theorder',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY'), ('Ousuka-Techno', 'Ousuka-Techno'), ('Eltartosiah', 'Eltartosiah'), ('Bielomatic', 'Bielomatic'), ('Lubricant_Engineers', 'Lubricant_Engineers'), ('Omega', 'Omega')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thepo',
            name='po_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thepo',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY'), ('Ousuka-Techno', 'Ousuka-Techno'), ('Eltartosiah', 'Eltartosiah'), ('Bielomatic', 'Bielomatic'), ('Lubricant_Engineers', 'Lubricant_Engineers'), ('Omega', 'Omega')], default='?', max_length=200, null=True),
        ),
    ]
