# Generated by Django 3.2.9 on 2021-12-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_auto_20211231_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thepo',
            name='store_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
