# Generated by Django 3.2.9 on 2021-11-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0012_monthmenets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthMenets',
        ),
    ]
