# Generated by Django 3.2.9 on 2021-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0013_alter_thepo_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorder',
            name='store_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
