# Generated by Django 3.2.9 on 2022-01-03 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0014_alter_theorder_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoffer',
            name='editable_r',
            field=models.ManyToManyField(related_name='editable_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theoffer',
            name='visible_to',
            field=models.ManyToManyField(related_name='visible_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
