# Generated by Django 3.2.9 on 2022-01-03 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0015_auto_20220103_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='thepo',
            name='edit_by',
            field=models.ManyToManyField(related_name='edit_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thepo',
            name='show_to',
            field=models.ManyToManyField(related_name='show_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
