# Generated by Django 3.2.9 on 2022-01-03 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0016_auto_20220103_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynotes',
            name='edit_it_by',
            field=models.ManyToManyField(related_name='edit_it_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailynotes',
            name='see_it_to',
            field=models.ManyToManyField(related_name='see_it_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
