# Generated by Django 3.2.9 on 2021-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0016_monthmenets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthmenets',
            name='monthtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
