# Generated by Django 3.2.9 on 2022-01-03 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0017_auto_20220103_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorder',
            name='editing_by',
            field=models.ManyToManyField(related_name='editing_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theorder',
            name='showing_to',
            field=models.ManyToManyField(related_name='showing_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
