# Generated by Django 3.2.9 on 2021-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0018_dailynotes_delete_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='delete_obj',
            field=models.CharField(blank=True, default='not-yet', max_length=100, null=True),
        ),
    ]
