# Generated by Django 3.2.9 on 2021-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0020_alter_dailynotes_delete_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynotes',
            name='update_obj',
            field=models.CharField(blank=True, default='Edit?', max_length=200, null=True),
        ),
    ]
