# Generated by Django 3.2.9 on 2021-11-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0022_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorder',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
