# Generated by Django 3.2.9 on 2021-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0025_theoffer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoffer',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thepo',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
