# Generated by Django 3.2.9 on 2021-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0027_thepo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
