# Generated by Django 3.2.9 on 2021-11-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0029_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.thepo'),
        ),
    ]
