# Generated by Django 3.2.9 on 2021-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0031_remove_customer_customer_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admins'),
        ),
    ]
