# Generated by Django 3.2.9 on 2021-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0033_alter_theorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
