# Generated by Django 3.2.9 on 2021-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0036_broadcast_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.RenameField(
            model_name='monthmenets',
            old_name='monthtitle',
            new_name='task_date',
        ),
        migrations.AddField(
            model_name='monthmenets',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj', 'CAP_Inj'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LVt'), ('BP460', 'BP460'), ('BP312', 'BP312')], default='Bp360AMP', max_length=100, null=True),
        ),
    ]
