# Generated by Django 3.2.9 on 2021-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0037_auto_20211128_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj', 'CAP_Inj'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LVt'), ('BP460', 'BP460'), ('BP312', 'BP312')], default='?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailynotes',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theoffer',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theorder',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thepo',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
    ]
