# Generated by Django 3.2.9 on 2021-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0038_auto_20211128_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
