# Generated by Django 3.2.9 on 2021-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0040_chessboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
        migrations.AlterField(
            model_name='dailynotes',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj', 'CAP_Inj'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LV'), ('BP460', 'BP460'), ('BP312', 'BP312')], default='?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthmenets',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj', 'CAP_Inj'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LV'), ('BP460', 'BP460'), ('BP312', 'BP312')], default='Bp360AMP', max_length=100, null=True),
        ),
    ]
