# Generated by Django 3.2.9 on 2021-12-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0041_auto_20211130_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj Nessie1', 'CAP_Inj Nessie1'), ('CAP_Inj Nessie2', 'CAP_Inj Nessie2'), ('CAP_Inj Arburg', 'CAP_Inj Arburg'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LV'), ('BP460', 'BP460'), ('BP312', 'BP312'), ('Micro-lab', 'Micro-lab')], default='?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthmenets',
            name='area',
            field=models.CharField(blank=True, choices=[('BM3', 'BM3'), ('BM4', 'BM4'), ('BM5', 'BM5'), ('BM6', 'BM6'), ('CAP_Inj Nessie1', 'CAP_Inj Nessie1'), ('CAP_Inj Nessie2', 'CAP_Inj Nessie2'), ('CAP_Inj Arburg', 'CAP_Inj Arburg'), ('CAP_assempl', 'CAP_assempl'), ('BP360AMP', 'BP360AMP'), ('BP360LV', 'BP360LV'), ('BP460', 'BP460'), ('BP312', 'BP312'), ('Micro-lab', 'Micro-lab')], default='Bp360AMP', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='product/')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.theoffer')),
            ],
        ),
    ]
