# Generated by Django 3.2.9 on 2021-12-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0042_auto_20211205_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
