# Generated by Django 3.2.9 on 2021-12-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0045_auto_20211206_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theoffer',
            name='user',
        ),
        migrations.AddField(
            model_name='theoffer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.customer'),
        ),
        migrations.AlterField(
            model_name='dailynotes',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theoffer',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='theorder',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thepo',
            name='vendor',
            field=models.CharField(blank=True, choices=[('Rommelag', 'Rommelag'), ('HENSE', 'HENSE'), ('ANGEPOT', 'ANGEPOT'), ('M_RASHAD', 'M_RASHAD'), ('HYDRAYLIC_SYSTEM', 'HYDRAYLIC_SYSTEM'), ('ELFARES', 'ELFARES'), ('ABO_ELILAA', 'ABO_ELILAA'), ('NEW_STAR_MOULD', 'NEW_STAR_MOULD'), ('ITALIX', 'ITALIX'), ('FESTO', 'FESTO'), ('SMC', 'SMC'), ('RS', 'RS'), ('NOORGREEN', 'NOORGREEN'), ('REXROTH', 'REXROTH'), ('TALAT_ELMASRY', 'TALAT_ELMASRY')], default='?', max_length=200, null=True),
        ),
    ]
