# Generated by Django 3.2.9 on 2021-12-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('utilitycheck_document', models.FileField(upload_to='utilitychecklist/docx/%Y/%m/%D/')),
            ],
        ),
    ]
