# Generated by Django 3.2.9 on 2022-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_utilitychecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=55)),
                ('event_name', models.CharField(max_length=55)),
                ('jan', models.CharField(max_length=2)),
                ('feb', models.CharField(max_length=2)),
                ('mar', models.CharField(max_length=2)),
                ('apr', models.CharField(max_length=2)),
                ('may', models.CharField(max_length=2)),
                ('jun', models.CharField(max_length=2)),
                ('jul', models.CharField(max_length=2)),
                ('aug', models.CharField(max_length=2)),
                ('sep', models.CharField(max_length=2)),
                ('oct', models.CharField(max_length=2)),
                ('nov', models.CharField(max_length=2)),
                ('dec', models.CharField(max_length=2)),
            ],
        ),
    ]
