# Generated by Django 3.2.9 on 2022-01-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_auto_20220102_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycalendar.event')),
                ('frequence', models.CharField(choices=[('YE', 'Yearly'), ('MO', 'Monthly'), ('WE', 'Weekly'), ('QA', 'Quarterly'), ('HA', 'Half_yearly')], default='WE', max_length=2)),
                ('interval', models.PositiveSmallIntegerField()),
            ],
            bases=('mycalendar.event',),
        ),
    ]
