# Generated by Django 3.2.9 on 2022-01-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_recurrentevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar',
            new_name='calendar_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('WR', 'work'), ('OT', 'audit'), ('MT', 'maintenance')], default='maintenance', max_length=2),
        ),
        migrations.DeleteModel(
            name='RecurrentEvent',
        ),
    ]
